# gradle/libs.versions.toml

[versions]
agp = "8.3.2"
kotlin = "1.9.25"

# AndroidX Core and AppCompat
core-ktx = "1.13.1"
appcompat = "1.7.0"
recyclerview = "1.3.2"
paletteKtx = "1.0.0"

# Android Lifecycle
lifecycle-viewmodel-ktx = "2.8.3"

# Navigation
navigation-fragment-ktx = "2.7.7"
navigation-ui-ktx = "2.7.7"
navigation-testing = "2.7.7"

# Work Manager
work-runtime-ktx = "2.9.1"

# ConstraintLayout
constraintlayout = "2.1.4"
constraintlayout-compose = "1.0.1"

# Compose Versions
activity-compose = "1.9.3"
compose-bom = "2024.09.03"

# Glance (AppWidgets)
glance-appwidget = "1.1.0"

# Other Libraries
commons-text = "1.12.0"
gson = "2.11.0"
biometric = "1.1.0"
material-icons-extended = "1.7.3"
glide = "4.16.0"

# AndroidX Test Libraries
espresso = "3.6.1"
test-core-ktx = "1.6.1"
test-runner = "1.6.2"
test-rules = "1.6.1"
fragment-testing = "1.8.3"
ui-test-junit4 = "1.7.3"
ui-test-manifest = "1.7.3"

[libraries]
# Core Libraries
core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "core-ktx" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
recyclerview = { group = "androidx.recyclerview", name = "recyclerview", version.ref = "recyclerview" }
palette-ktx = { group = "androidx.palette", name = "palette-ktx", version.ref = "paletteKtx" }

# Android Lifecycle
lifecycle-viewmodel-ktx = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-ktx", version.ref = "lifecycle-viewmodel-ktx" }

# Navigation
navigation-fragment-ktx = { group = "androidx.navigation", name = "navigation-fragment-ktx", version.ref = "navigation-fragment-ktx" }
navigation-ui-ktx = { group = "androidx.navigation", name = "navigation-ui-ktx", version.ref = "navigation-ui-ktx" }
navigation-testing = { group = "androidx.navigation", name = "navigation-testing", version.ref = "navigation-testing" }

# Work Manager
work-runtime-ktx = { group = "androidx.work", name = "work-runtime-ktx", version.ref = "work-runtime-ktx" }

# ConstraintLayout
constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
constraintlayout-compose = { group = "androidx.constraintlayout", name = "constraintlayout-compose", version.ref = "constraintlayout-compose" }

# Compose (using BOM)
compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "compose-bom" }
activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activity-compose" }
compose-android = { group = "androidx.compose.runtime", name = "runtime-android" }
compose-material3 = { group = "androidx.compose.material3", name = "material3" }
compose-animation = { group = "androidx.compose.animation", name = "animation" }
compose-ui = { group = "androidx.compose.ui", name = "ui" }
compose-foundation = { group = "androidx.compose.foundation", name = "foundation" }
compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }

# Glance (AppWidgets)
glance-appwidget = { group = "androidx.glance", name = "glance-appwidget", version.ref = "glance-appwidget" }

# Miscellaneous Libraries
commons-text = { group = "org.apache.commons", name = "commons-text", version.ref = "commons-text" }
gson = { group = "com.google.code.gson", name = "gson", version.ref = "gson" }
biometric = { group = "androidx.biometric", name = "biometric", version.ref = "biometric" }
material-icons-extended = { group = "androidx.compose.material", name = "material-icons-extended", version.ref = "material-icons-extended" }
glide = { group = "com.github.bumptech.glide", name = "glide", version.ref = "glide" }

# Testing Libraries
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espresso" }
espresso-contrib = { group = "androidx.test.espresso", name = "espresso-contrib", version.ref = "espresso" }
espresso-idling-resource = { group = "androidx.test.espresso", name = "espresso-idling-resource", version.ref = "espresso" }
test-core-ktx = { group = "androidx.test", name = "core-ktx", version.ref = "test-core-ktx" }
test-runner = { group = "androidx.test", name = "runner", version.ref = "test-runner" }
test-rules = { group = "androidx.test", name = "rules", version.ref = "test-rules" }
fragment-testing = { group = "androidx.fragment", name = "fragment-testing", version.ref = "fragment-testing" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
jetbrains-kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }